import { gql, useLazyQuery, useMutation, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Footer } from "../../components/footer";
import HeadIcon from "../../components/head_icon";
import InitFont from "../../components/initialize_font";
import Navbar from "../../components/navbar";
import RupiahFormat from "../../misc/currency";
import Shop from "../../models/Shop";
import styles from "../../styles/Shipment.module.scss";
import PlacesAutocomplete, {
  geocodeByAddress,
  getLatLng,
} from "react-places-autocomplete";
import LocationSearchInput from "./test";

const Shipment: NextPage = () => {
  const [address, setAddress] = useState("");
  const [prevSet, setPrevSet] = useState(new Set());
  const [cartsQty, setCartsQty] = useState([]);
  const [cartSummary, setCartSummary] = useState({
    quantity: 0,
    original: 0,
    discount: 0,
  });

  const CHECKOUT_CARTS_QUERY = gql`
    query GetUserCheckedCart {
      getUserCheckedCart {
        id
        checked
        quantity
        product {
          id
          name
          discount
          price
          stock
          shop {
            id
            name
            city
            type
          }
          images {
            image
          }
        }
      }
    }
  `;

  const {
    loading: checkoutLoading,
    error: checkoutError,
    data: checkoutData,
  } = useQuery(CHECKOUT_CARTS_QUERY, {
    pollInterval: 500,
  });

  useEffect(() => {
    let totalQuantity = 0;
    let totalOriginalPrice = 0;
    let totalDiscountedPrice = 0;
    checkoutData?.getUserCheckedCart?.map((cart: any) => {
      if (cart?.checked === true) {
        totalQuantity += cart?.quantity;
        totalOriginalPrice += cart?.product?.price * cart?.quantity;
        totalDiscountedPrice +=
          (cart?.product?.price * cart?.quantity * cart?.product?.discount) /
          100;
      }
    });
    setCartSummary({
      quantity: totalQuantity,
      original: totalOriginalPrice,
      discount: totalDiscountedPrice,
    });
    console.log(
      checkoutData?.getUserCheckedCart
        ?.map((cart: any) => cart?.product?.shop)
        .filter(
          (value: any, index: any, self: string | any[]) =>
            self.indexOf(value) === index
        )
    );
    // console.log(checkoutData)
    // console.log(checkoutData?.getUserCheckedCart?.carts.map((cart: any) => cart?.product?.shop).filter((value: any, index: any, self: string | any[]) => self.indexOf(value) === index))
  }, [checkoutData]);

  function getCart(cartId: string) {
    return checkoutData?.getUserCheckedCart?.filter((cart: any) => {
      return cart.id === cartId;
    })[0];
  }

  function getShopSubTotal(shopId: string) {
    let subTotal = 0;
    getShopCarts(shopId).map((cart: any) => {
      subTotal += (cart?.product?.price * cart?.quantity * (100 - cart?.product?.discount)) / 100;
    });

    return subTotal
  }

  function getShopCarts(shopId: string) {
    return checkoutData?.getUserCheckedCart?.filter((cart: any) => {
      return cart?.product?.shop?.id === shopId;
    });
  }

  // console.log(google?.maps)
  // console.log(window ? window?.google : null)
  console.log(address);
  return (
    <div className={styles.container}>
      <Head>
        <title>Checkout | Tohopedia</title>
        <meta name="description" content="Generated by create next app" />
        {1 == 1 ? (
          <link rel="icon" href="/logo/tohopedia-favicon.png" />
        ) : (
          <link rel="icon" href="/logo/tohopedia-favicon-notif.ico" />
        )}
      </Head>
      <InitFont />
      <Navbar />
      <main className={styles.main}>
        <div className={styles.main_checkout_container}>
          <div className={styles.checkout_left_outer_container}>
            <div className={styles.checkout_left_inner_container}>
              <div className={styles.checkout_left_container}>
                <div>
                  <h1 className={styles.checkout_header_h1}>Checkout</h1>
                  <div className={styles.checkout_address_outer_container}>
                    <div className={styles.checkout_address_inner_container}>
                      <div className={styles.checkout_address_header}>
                        Alamat Pengiriman
                      </div>
                      <div className={styles.checkout_address_main_container}>
                        <div>
                          <div
                            className={styles.checkout_address_label_container}
                          >
                            <b
                              className={styles.checkout_address_label_receiver}
                            >
                              Winston Khoe
                            </b>
                            <span className={styles.checkout_address_label_tag}>
                              (Winston Khoe Main)
                            </span>
                            <div className={styles.checkout_address_label_main}>
                              Utama
                            </div>
                          </div>
                        </div>
                        <div className={styles.checkout_address_phone}>
                          6281315174786
                        </div>
                        <div
                          className={styles.checkout_address_detail_container}
                        >
                          <div className={styles.checkout_address_detail}>
                            Jl. Janur Hijau 1 Blok AF 15 No.7, Sektor 1A
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles.checkout_address_options_container}
                      >
                        <button
                          className={styles.checkout_address_options_button}
                        >
                          <span className={styles.checkout_address_button_text}>
                            Pilih Alamat Lain
                          </span>
                        </button>
                      </div>
                    </div>
                  </div>
                  {/* LIST PESANAN Container */}
                  <div className={styles.checkout_order_list_container}>
                    {checkoutData?.getUserCheckedCart
                      ?.map((cart: any) => cart?.product?.shop)
                      .filter(
                        (value: any, index: any, self: string | any[]) =>
                          self.indexOf(value) === index
                      )
                      .map((shop: any, index: number) => {
                        {
                          /* ONE PESANAN CONTAINER */
                        }
                        return (
                          <div
                            key={shop?.id}
                            className={styles.checkout_order_container}
                          >
                            <p className={styles.checkout_order_header}>
                              Pesanan {index + 1}
                            </p>
                            <div
                              className={styles.checkout_order_detail_container}
                            >
                              <div>
                                <div
                                  className={styles.checkout_order_shop_details}
                                >
                                  <div
                                    className={
                                      styles.checkout_order_shop_details_inner
                                    }
                                  >
                                    <div
                                      className={
                                        styles.checkout_order_shop_details_inner_left
                                      }
                                    >
                                      <div>
                                        <div
                                          className={
                                            styles.checkout_order_shop_name_type
                                          }
                                        >
                                          <div
                                            className={
                                              styles.checkout_order_shop_type_relative
                                            }
                                          >
                                            <Image
                                              src={`/logo/${
                                                shop?.type == 1
                                                  ? "badge_pm.png"
                                                  : shop?.type == 2
                                                  ? "badge_pmp.svg"
                                                  : shop?.type == 3
                                                  ? "badge_os.png"
                                                  : null
                                              }`}
                                              alt=""
                                              layout="fill"
                                            />
                                          </div>
                                          <span
                                            className={
                                              styles.checkout_order_shop_name
                                            }
                                          >
                                            {shop?.name}
                                          </span>
                                        </div>
                                        <div
                                          className={
                                            styles.checkout_order_shop_city_container
                                          }
                                        >
                                          <p
                                            className={
                                              styles.checkout_order_shop_city
                                            }
                                          >
                                            {shop?.city}
                                          </p>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div
                                  className={
                                    styles.checkout_order_details_outer_container
                                  }
                                >
                                  <div
                                    className={
                                      styles.checkout_order_details_inner_container
                                    }
                                  >
                                    {/* Item Container */}
                                    <div
                                      className={
                                        styles.checkout_order_details_products_container
                                      }
                                    >
                                      {getShopCarts(shop?.id).map(
                                        (cart: any, index: number) => {
                                          return (
                                            <div
                                              key={cart?.id}
                                              className={
                                                styles.checkout_order_details_products_inner_container
                                              }
                                            >
                                              <div
                                                className={
                                                  styles.checkout_order_individual_detail_product_outer_container
                                                }
                                              >
                                                <div
                                                  className={
                                                    styles.checkout_order_individual_detail_product_inner_container
                                                  }
                                                >
                                                  <div
                                                    className={
                                                      styles.checkout_order_individual_detail_product_container
                                                    }
                                                  >
                                                    <div
                                                      className={
                                                        styles.checkout_order_product_image
                                                      }
                                                    >
                                                      <div
                                                        className={
                                                          styles.checkout_order_product_image_container
                                                        }
                                                      >
                                                        <div
                                                          className={
                                                            styles.checkout_order_product_image_relative
                                                          }
                                                        >
                                                          <Image
                                                            src={`/uploads/${cart?.product?.images[0]?.image}`}
                                                            alt=""
                                                            layout="fill"
                                                            objectFit="cover"
                                                          />
                                                        </div>
                                                      </div>
                                                    </div>
                                                    <div
                                                      className={
                                                        styles.checkout_order_product_detail_container
                                                      }
                                                    >
                                                      <p
                                                        className={
                                                          styles.checkout_order_product_name
                                                        }
                                                      >
                                                        {cart?.product?.name}
                                                      </p>
                                                      <div
                                                        className={
                                                          styles.checkout_order_product_variant_quantity
                                                        }
                                                      >
                                                        <p
                                                          className={
                                                            styles.checkout_order_product_variant
                                                          }
                                                        >
                                                          1400 GSM
                                                        </p>
                                                        <p
                                                          className={
                                                            styles.checkout_order_product_quantity
                                                          }
                                                        >
                                                          {cart?.quantity}{" "}
                                                          barang
                                                        </p>
                                                      </div>
                                                      <div
                                                        className={
                                                          styles.checkout_order_product_price_container
                                                        }
                                                      >
                                                        {cart?.product
                                                          ?.discount > 0 ? (
                                                          <p
                                                            className={
                                                              styles.checkout_order_product_price_discount
                                                            }
                                                          >
                                                            {RupiahFormat(
                                                              cart?.product
                                                                ?.price *
                                                                cart?.quantity
                                                            )}
                                                          </p>
                                                        ) : null}

                                                        <p
                                                          className={
                                                            styles.checkout_order_product_price_original
                                                          }
                                                        >
                                                          {RupiahFormat(
                                                            (cart?.product
                                                              ?.price *
                                                              cart?.quantity *
                                                              (100 -
                                                                cart?.product
                                                                  ?.discount)) /
                                                              100
                                                          )}
                                                        </p>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          );
                                        }
                                      )}
                                    </div>
                                    {/* END Item Container */}
                                    <div
                                      className={
                                        styles.checkout_order_details_delivery_container
                                      }
                                    >
                                      <div
                                        className={
                                          styles.checkout_order_details_delivery_header
                                        }
                                      >
                                        Pilih Durasi
                                      </div>
                                      <select
                                        className={
                                          styles.checkout_order_details_delivery_options
                                        }
                                        name=""
                                        id=""
                                      >
                                        <option value="">Reguler</option>
                                        <option value="">Kargo</option>
                                        <option value="">Ekonomi</option>
                                      </select>
                                    </div>
                                  </div>
                                </div>

                                <div
                                  className={
                                    styles.checkout_order_detail_subtotal
                                  }
                                >
                                  <div
                                    className={
                                      styles.checkout_order_detail_subtotal_inner
                                    }
                                  >
                                    <div
                                      className={
                                        styles.checkout_order_detail_subtotal_container
                                      }
                                    >
                                      <p
                                        className={
                                          styles.checkout_order_detail_subtotal_label
                                        }
                                      >
                                        Subtotal
                                      </p>
                                      <p
                                        className={
                                          styles.checkout_order_detail_subtotal_price
                                        }
                                      >
                                        {RupiahFormat(getShopSubTotal(shop?.id))}
                                      </p>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        );
                        {
                          /* END ONE PESANAN CONTAINER */
                        }
                      })}
                  </div>
                  {/* END LIST PESANAN Container */}
                </div>
              </div>
            </div>
          </div>

          {/* Summary Container */}
          <div className={styles.cart_summary_outer_container}>
            <div className={styles.cart_summary_inner_container}>
              <div className={styles.cart_summary_container}>
                <section className={styles.cart_summary_section}>
                  <div className={styles.promo_outer_container}>
                    <div className={styles.promo_inner_container}>
                      <div className={styles.promo_icon_container}>
                        <Image
                          src={"/logo/icon_promo.svg"}
                          alt=""
                          layout="fill"
                        />
                      </div>
                      <div className={styles.promo_text_container}>
                        <span className={styles.promo_text}>
                          Makin hemat pakai promo
                        </span>
                      </div>
                      <div className={styles.promo_icon_arrow_container}>
                        <Image
                          src={"/logo/icon_arrow_right.svg"}
                          alt=""
                          layout="fill"
                        />
                      </div>
                    </div>
                  </div>
                  <div className={styles.cart_summary_separator}></div>
                  <div className={styles.cart_main_summary_container}>
                    <div>
                      <h6 className={styles.cart_main_summary_header}>
                        Ringkasan belanja
                      </h6>
                      <div className={styles.cart_main_summary_lists_container}>
                        <p className={styles.cart_main_summary_total_item}>
                          Total Harga ({cartSummary.quantity} barang)
                        </p>
                        <p
                          className={styles.cart_main_summary_total_item_price}
                        >
                          {RupiahFormat(cartSummary.original)}
                        </p>
                      </div>
                      {cartSummary.discount > 0 ? (
                        <div
                          className={styles.cart_main_summary_lists_container}
                        >
                          <p className={styles.cart_main_summary_total_item}>
                            Total Diskon Barang
                          </p>
                          <p
                            className={
                              styles.cart_main_summary_total_item_price
                            }
                          >
                            -{RupiahFormat(cartSummary.discount)}
                          </p>
                        </div>
                      ) : null}

                      <hr className={styles.cart_main_summary_separator} />
                      <div
                        className={
                          styles.cart_main_summary_final_price_container
                        }
                      >
                        <h6 className={styles.cart_main_summary_price_label}>
                          Total Tagihan
                        </h6>
                        <h6 className={styles.cart_main_summary_price_value}>
                          {cartSummary.original > 0
                            ? RupiahFormat(
                                cartSummary.original - cartSummary.discount
                              )
                            : "-"}
                        </h6>
                      </div>
                    </div>
                    <div
                      className={styles.cart_main_summary_buy_button_container}
                    >
                      <button
                        className={
                          cartSummary.quantity > 0
                            ? styles.cart_main_summary_buy_button_available
                            : styles.cart_main_summary_buy_button_disable
                        }
                      >
                        <span
                          className={styles.cart_main_summary_buy_button_text}
                        >
                          Bayar
                        </span>
                      </button>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
          {/* END SUMMARY CONTAINER */}
        </div>
      </main>

      <Footer />
    </div>
  );
};
export default Shipment;
