import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import { stateContext } from "../../services/StateProvider";
import Footer from "../Footer/Footer";
import InitFont from "../initialize_font";
import Navbar from "../navbar";
import styles from "./PageLayout.module.scss"

const PageLayout = (props: { children: any }) => {
  const router = useRouter();
  const { pageTitle } = useContext(stateContext)
  const noNavbar = ["login", "register"]
  
  function checkPathExists(array: any, path: string) {
    return array.indexOf(path) >= 0;
  }
  
  const paths = router.pathname.split("/");

  function checkList(pathList: string[], array: string[]): boolean {
    let counter = 0;

    array.map((str: string) => {
      if (pathList.indexOf(str) >= 0) {
        counter++;
      }
    })
    return counter == 0
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{pageTitle}</title>
        {/* <title>Home | Tohopedia</title> */}
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {1 == 1 ? (
          <link rel="icon" href="/logo/tohopedia-favicon.png" />
        ) : (
          <link rel="icon" href="/logo/tohopedia-favicon-notif.ico" />
        )}
      </Head>
      <InitFont />
      {checkList(paths, noNavbar) == true ? <Navbar /> : null }
        {props.children}
      {checkList(paths, noNavbar) == true ? <Footer /> : null }
    </div>
  );
};

export default PageLayout;
