import Head from "next/head";
import { useContext } from "react";
import { stateContext } from "../../services/StateProvider";
import Footer from "../Footer/Footer";
import InitFont from "../initialize_font";
import Navbar from "../navbar";
import styles from "./PageLayout.module.scss"

const PageLayout = (props: { children: any }) => {
  const {pageTitle} = useContext(stateContext)
  return (
    <div className={styles.container}>
      <Head>
        <title>{pageTitle}</title>
        {/* <title>Home | Tohopedia</title> */}
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {1 == 1 ? (
          <link rel="icon" href="/logo/tohopedia-favicon.png" />
        ) : (
          <link rel="icon" href="/logo/tohopedia-favicon-notif.ico" />
        )}
      </Head>
      <InitFont />
      <Navbar />
          {props.children}
      <Footer />
    </div>
  );
};

export default PageLayout;
