import { gql, useLazyQuery, useMutation, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Navbar from "../components/navbar";
import styles from "../styles/login.module.scss";
import { useForm } from "react-hook-form";
import { redirect } from "next/dist/server/api-utils";
import Router, { useRouter } from "next/router";
import { checkCookies, setCookies } from 'cookies-next';
import InitFont from "../components/initialize_font";

const Login: NextPage = () => {
  const { register, handleSubmit } = useForm();
  const [result, setResult] = useState("");

  const [name, setName] = useState("");
  var element = "";
  const router = useRouter()

  const LOGIN_MUTATION = gql`
    mutation auth($email: String!, $password: String!) {
      auth {
        login(email: $email, password: $password)
      }
    }
  `;

  const [getLogin, { loading, error, data }] = useMutation(LOGIN_MUTATION);

  async function onSubmit(formData: any) {
    try {
      getLogin({
        variables: {
          email: formData.email,
          password: formData.password,
        },
      }).then((data: any) => {
          setCookies('tokenid', data.data.auth.login.token)
          const returnUrl = router.query.returnUrl || '/';
          router.push(returnUrl)
      });
      
    } catch (error) {
      console.log(error)      
    }
  }


  // if (data) {
  //   setCookies('tokenid', data.auth.login.token)
  //   Router.push('/')
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Masuk / Login | Tohopedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <InitFont/>
      </Head>
      {/* <Navbar/> */}
      <div className={styles.container}>
        {/* Header */}
        <div className={styles.header}>
          <Link href="/">
            <div>
              <Image 
                src="/logo/tohopedia_logo.png"
                alt="tohopedia logo"
                layout="fill"
                priority
              />
            </div>
          </Link>
        </div>

        {/* Login Body */}
        <div className={styles.body}>
          <div className={styles.login_image}>
            <Image
              src="/assets/login_image.png"
              alt="tohopedia logo"
              layout="fill"
              priority
            />
          </div>
          <section>
            <div className={styles.section_header}>
              <h3>Masuk</h3>
              <Link href="/register">
                <a>Daftar</a>
              </Link>
            </div>
            <div className={styles.section_body}>
              <form autoComplete="on" onSubmit={handleSubmit(onSubmit)}>
                <div className={styles.label_fields_container}>
                  <label htmlFor="email">Email</label>
                  <div tabIndex={-1}>
                    <input type="email" {...register("email")} />
                  </div>
                </div>

                <div className={styles.label_fields_container}>
                  <label htmlFor="email">Kata Sandi</label>
                  <div tabIndex={-1}>
                    <input type="password" {...register("password")} />
                  </div>
                </div>

                {/* Ingat Saya && Lupa kata sandi */}
                <div className={styles.remember_forget_container}>
                  {/* Remember Me */}
                  <div>
                    <div className={styles.remember_me}>
                      <label htmlFor="remember-me">
                        <input type="checkbox" name="" id="remember_me" />
                        <span></span>
                      </label>
                    </div>
                    <span>Ingat Saya</span>
                  </div>
                </div>
                <button type="submit">
                  <span>Masuk</span>
                </button>
              </form>
            </div>
          </section>
        </div>
        {/* End Login Body */}
      </div>
    </div>
  );
};

export default Login;
