import { gql, useLazyQuery, useMutation, useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Navbar from "../components/navbar";
import styles from "../styles/login.module.scss";
import { useForm } from "react-hook-form";
import { redirect } from "next/dist/server/api-utils";
import Router from "next/router";

const Register: NextPage = () => {
  const { register, handleSubmit } = useForm();
  const [result, setResult] = useState("");

  const [name, setName] = useState("");
  var element = "";

  const LOGIN_QUERY = gql`
    mutation auth($email: String!, $password: String!) {
      auth {
        login(email: $email, password: $password)
      }
    }
  `;

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      console.log(name);
      // Send Axios request here
    }, 3000);

    return () => clearTimeout(delayDebounceFn);
  }, [name]);

  const [getLogin, { loading, error, data }] = useMutation(LOGIN_QUERY);

  async function onSubmit(formData: any) {
    try {
      await getLogin({
        variables: {
          email: formData.email,
          password: formData.password,
        },
      });
      Router.push('/')
    } catch (error) {
      console.log(error)      
    }
  }

  if (data) {
    console.log(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Masuk / Login | Tohopedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Open_Sans/static/OpenSans/OpenSans-Bold.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      {/* <Navbar/> */}
      <div className={styles.container}>
        {/* Header */}
        <div className={styles.header}>
          <Link href="/">
            <div>
              <Image
                src="/logo/tohopedia_logo.png"
                alt="tohopedia logo"
                layout="fill"
              />
            </div>
          </Link>
        </div>

        {/* Login Body */}
        <div className={styles.body}>
          <div className={styles.login_image}>
            <Image
              src="/assets/login_image.png"
              alt="tohopedia logo"
              layout="fill"
            />
          </div>
          <section>
            <div className={styles.section_header}>
              <h3>Masuk</h3>
              <Link href="/register">
                <a>Daftar</a>
              </Link>
            </div>
            <div className={styles.section_body}>
              <form autoComplete="on" onSubmit={handleSubmit(onSubmit)}>
                <div className={styles.label_fields_container}>
                  <label htmlFor="email">Email</label>
                  <div tabIndex={-1}>
                    <input type="email" {...register("email")} />
                  </div>
                </div>

                <div className={styles.label_fields_container}>
                  <label htmlFor="email">Kata Sandi</label>
                  <div tabIndex={-1}>
                    <input type="password" {...register("password")} />
                  </div>
                </div>

                {/* Ingat Saya && Lupa kata sandi */}
                <div className={styles.remember_forget_container}>
                  {/* Remember Me */}
                  <div>
                    <div className={styles.remember_me}>
                      <label htmlFor="remember-me">
                        <input type="checkbox" name="" id="remember_me" />
                        <span></span>
                      </label>
                    </div>
                    <span>Ingat Saya</span>
                  </div>
                </div>
                <button type="submit">
                  <span>Masuk</span>
                </button>
              </form>
            </div>
          </section>
        </div>
        {/* End Login Body */}
      </div>
    </div>
  );
};

export default Register;
